### PR TITLE
Feat/fix att

### PR DESCRIPTION
**Pull request by macintoshpie**
A few small changes to handle edge cases. I believe it is now ready to be run on the server data.

@nllong @corymosiman12 please review the known issues below and comment. These are the differences when comparing the transformed file with itself after importing and exporting from Audit Template Tool.
## Known Issues
- Id's will be changed (as a result Property Name will be chanced in SEED because that's where we get the value from)
- Some PremisesIdentifiers are dropped
  - Assessor Parcel Number
- FloorsAboveGrade and FloorsBelowGrade are dropped
- Scenarios:
  - all Scenarios are dropped along with their TimeSeries data

### CODE REVIEW

**Comment by corymosiman12** [comment]
Notes:
- Added item to discuss with ATT about round-tripping files w/specific IDs - would like element IDs not to be stripped / replaced

@macintoshpie, based on email chain w/Borkum from 4/15, have you tried this:
>I got more info from Richard. Please use “BRICR Phase 0 Report” for the Audit Template report type user-defined field and “City Custom Building ID” for the “Assessor parcel number” premises identifier.

We definitely want the parcel# to roundtrip, so if we need to change the report type / UDF then I guess we should do it.

**Comment by macintoshpie** [comment]
Thanks Cory, I am using `BRICR Phase 0/1`

I tried to change Assessor parcel number to something like below but it's still getting removed. I tried removing the "SF" prefix on the ID as well (thought maybe it only accepted ints) but it was still removed. Might be worth bringing up with ATT folks as well.
```
<auc:PremisesIdentifier>
  <auc:IdentifierLabel>Custom</auc:IdentifierLabel>
    <auc:IdentifierCustomName>City Custom Building ID</auc:IdentifierCustomName>
    <auc:IdentifierValue>{{IDHERE}}</auc:IdentifierValue>
</auc:PremisesIdentifier>
```

I also tried adding a UDF to contain the data in auc:Building as well as auc:Report but both were dropped on the ATT export

**Comment by macintoshpie** [comment]
Waiting for feedback on user testing from BRICR folks to make sure these transformations are sufficient before merging.

**Comment by corymosiman12** [comment]
Thanks Ted!

**Comment by nllong** [comment]
@macintoshpie -- I think we can merge this, any objections?

**Comment by macintoshpie** [comment]
@nllong yes please, let's merge this

**Comment by nllong** [comment]
@macintoshpie --done

**Pull request merged**
